############# English navigation ##############

# main menu
[[main]]
name = "Federal Science DataHub"
url = "/"
weight = 1
identifier = "home"

[[main]]
name = "Product"
url = "/product"
weight = 2

[[main]]
name = "Overview"
parent = "Product"
url = "/product"
weight = 1

[[main]]
name = "Storage"
parent = "Product"
url = "/product/storage"
weight = 2

[[main]]
name = "Databricks"
parent = "Product"
url = "/product/databricks"
weight = 3

[[main]]
name = "Azure App Service"
parent = "Product"
url = "/product/app-service"
weight = 5

[[main]]
name = "PostgreSQL"
parent = "Product"
url = "/product/postgresql"
weight = 4

[[main]]
name = "External integrations"
parent = "Product"
url = "/product/integrations"
weight = 6

[[main]]
name = "Resources"
url = "/resources"
weight = 3

[[main]]
name = "Knowledge base"
parent = "Resources"
url = "/knowledge-base"
weight = 1

[[main]]
name = "Product updates"
parent = "Resources"
url = "/updates"
weight = 2

[[main]]
name = "Get involved"
parent = "Resources"
url = "/get-involved"
weight = 3

[[main]]
name = "About"
url = "/about"
weight = 4

[[main]]
name = "Background"
parent = "About"
url = "/about"
weight = 1

[[main]]
name = "Innovation Roadmap"
parent = "About"
url = "/about/roadmap"
weight = 2

[[main]]
name = "News"
parent = "About"
url = "/about/news"
weight = 3

[[main]]
name = "Terms and conditions"
parent = "About"
url = "/about/terms-and-conditions"
weight = 4

[[main]]
name = "Privacy"
parent = "About"
url = "/about/privacy"
weight = 5

[[main]]
name = "Security"
parent = "About"
url = "/about/security"
weight = 6

[[main]]
name = "Contact us"
parent = "About"
url = "/contact"
weight = 7

[[main]]
name = "Log in"
url = "https://poc.fsdh-dhsf.science.cloud-nuage.canada.ca/"
weight = 16
